package programodpytanie.paneledycji.panelelisty;

import java.awt.Container;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import programodpytanie.ListaKomponentowDoAktywacji;
import programodpytanie.ObslugaOkienka;
import programodpytanie.ObslugaPliku;

public class PanelListaDodaj extends javax.swing.JPanel {

    public PanelListaDodaj() {
	initComponents();
        myOptions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eOpis = new javax.swing.JLabel();
        pDodawania = new javax.swing.JPanel();
        eAngielskieSlowo = new javax.swing.JLabel();
        tfPolski = new javax.swing.JTextField();
        tfAngielski = new javax.swing.JTextField();
        gZapisz = new javax.swing.JButton();
        ePolskieSlowo = new javax.swing.JLabel();
        eKomunikat = new javax.swing.JLabel();
        gZapiszDoPliku = new javax.swing.JButton();

        eOpis.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        eOpis.setText("Dodaj nowy zestaw słówek");

        eAngielskieSlowo.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        eAngielskieSlowo.setText("Po angielsku:");

        tfPolski.setColumns(15);
        tfPolski.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        tfPolski.setMinimumSize(new java.awt.Dimension(56, 19));

        tfAngielski.setColumns(15);
        tfAngielski.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        tfAngielski.setMinimumSize(new java.awt.Dimension(56, 19));

        gZapisz.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        gZapisz.setText("Zapisz");
        gZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gZapiszActionPerformed(evt);
            }
        });

        ePolskieSlowo.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        ePolskieSlowo.setText("Po polsku: ");

        eKomunikat.setText("Powiodło/nie powiodło się");

        gZapiszDoPliku.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        gZapiszDoPliku.setText("Zapisz do pliku");
        gZapiszDoPliku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gZapiszDoPlikuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDodawaniaLayout = new javax.swing.GroupLayout(pDodawania);
        pDodawania.setLayout(pDodawaniaLayout);
        pDodawaniaLayout.setHorizontalGroup(
            pDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDodawaniaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gZapiszDoPliku)
                    .addGroup(pDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pDodawaniaLayout.createSequentialGroup()
                            .addGroup(pDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ePolskieSlowo)
                                .addComponent(eAngielskieSlowo))
                            .addGap(25, 25, 25)
                            .addGroup(pDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfAngielski, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfPolski, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDodawaniaLayout.createSequentialGroup()
                            .addComponent(eKomunikat)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gZapisz))))
                .addGap(107, 107, 107))
        );
        pDodawaniaLayout.setVerticalGroup(
            pDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDodawaniaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ePolskieSlowo)
                    .addComponent(tfPolski, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eAngielskieSlowo)
                    .addComponent(tfAngielski, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gZapisz)
                    .addComponent(eKomunikat))
                .addGap(15, 15, 15)
                .addComponent(gZapiszDoPliku))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(eOpis))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(pDodawania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eOpis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pDodawania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void myOptions(){
        this.eKomunikat.setText("");
    }
    
    private void gZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gZapiszActionPerformed
        zapiszDoTablicy(false);
    }//GEN-LAST:event_gZapiszActionPerformed

    private void gZapiszDoPlikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gZapiszDoPlikuActionPerformed
        zapiszDoTablicy(true);
    }//GEN-LAST:event_gZapiszDoPlikuActionPerformed

    
    public void zapiszDoTablicy(boolean czyTezDoPliku){
        
        Container edycja = (this.getParent()).getParent();
        
	// Walidacja
        if(tfPolski.getText().equals("") || tfAngielski.getText().equals("")){
            JOptionPane.showMessageDialog(edycja, "Podaj słowa!");
            return;
        }
	
	ObslugaPliku.getPytania().add(tfPolski.getText());
	ObslugaPliku.getOdpowiedzi().add(tfAngielski.getText());
	
	if(czyTezDoPliku && JOptionPane.showConfirmDialog(edycja, "Czy na pewno chcesz zapisać do pliku?", "Uwaga!", JOptionPane.YES_NO_OPTION) == 0){
	    String[] pytanie = { tfPolski.getText() },
		     odpowiedz = { tfAngielski.getText() };
	    String komunikat = ObslugaPliku.zapisDoPliku(pytanie, odpowiedz, true);
	    if(komunikat.equals("0"))
		this.eKomunikat.setText("Zapis powiódł się.");
	    else{
		JOptionPane.showMessageDialog(edycja, komunikat, "Nieudany zapis", JOptionPane.ERROR_MESSAGE);
		this.eKomunikat.setText("");
	    }
	}
	
	this.eKomunikat.setText("Zapis powiódł się.");
	
	ObslugaPliku.setIloscStron();
        ObslugaPliku.setCzyMaZawartosc(ObslugaPliku.getPytania().size() != 0);
	ListaKomponentowDoAktywacji.ustawKomponent(ObslugaPliku.getCzyMaZawartosc());
	tfPolski.setText("");
	tfAngielski.setText("");
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eAngielskieSlowo;
    private javax.swing.JLabel eKomunikat;
    private javax.swing.JLabel eOpis;
    private javax.swing.JLabel ePolskieSlowo;
    private javax.swing.JButton gZapisz;
    private javax.swing.JButton gZapiszDoPliku;
    private javax.swing.JPanel pDodawania;
    private javax.swing.JTextField tfAngielski;
    private javax.swing.JTextField tfPolski;
    // End of variables declaration//GEN-END:variables
}
