package programodpytanie.paneledycji.panelelisty;

import java.awt.Container;
import javax.swing.JOptionPane;
import programodpytanie.Edycja;
import programodpytanie.ListaKomponentowDoAktywacji;
import programodpytanie.ListaSlowek;
import programodpytanie.ObslugaOkienka;
import programodpytanie.ObslugaPliku;


public class PanelListaUsun extends javax.swing.JPanel {

    private ListaSlowek listaSlowek;
    
    private Edycja edycja;
    
    public PanelListaUsun(Edycja edycja) {
	initComponents();
	this.edycja = edycja;
	listaSlowek = new ListaSlowek();
	listaSlowek.myOptions(pListaSlowek);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eOpis = new javax.swing.JLabel();
        pDodawania = new javax.swing.JPanel();
        eNumerZestawu = new javax.swing.JLabel();
        tfNumerZestawu = new javax.swing.JTextField();
        eKomunikat = new javax.swing.JLabel();
        gZapisz = new javax.swing.JButton();
        gZapiszPlik = new javax.swing.JButton();
        pListaSlowek = new javax.swing.JPanel();

        eOpis.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        eOpis.setText("Usuń zestaw słówek");

        eNumerZestawu.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        eNumerZestawu.setText("Numer zestawu:");

        tfNumerZestawu.setColumns(15);
        tfNumerZestawu.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        tfNumerZestawu.setMinimumSize(new java.awt.Dimension(56, 19));
        tfNumerZestawu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumerZestawuActionPerformed(evt);
            }
        });

        gZapisz.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        gZapisz.setText("Zapisz");
        gZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gZapiszActionPerformed(evt);
            }
        });

        gZapiszPlik.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        gZapiszPlik.setText("Zapisz do pliku");
        gZapiszPlik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gZapiszPlikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDodawaniaLayout = new javax.swing.GroupLayout(pDodawania);
        pDodawania.setLayout(pDodawaniaLayout);
        pDodawaniaLayout.setHorizontalGroup(
            pDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDodawaniaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDodawaniaLayout.createSequentialGroup()
                        .addComponent(eNumerZestawu)
                        .addGap(25, 25, 25)
                        .addComponent(tfNumerZestawu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(93, Short.MAX_VALUE))
                    .addGroup(pDodawaniaLayout.createSequentialGroup()
                        .addComponent(eKomunikat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gZapisz)
                        .addGap(23, 23, 23))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDodawaniaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gZapiszPlik)
                .addContainerGap())
        );
        pDodawaniaLayout.setVerticalGroup(
            pDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDodawaniaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNumerZestawu)
                    .addComponent(tfNumerZestawu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDodawaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eKomunikat)
                    .addComponent(gZapisz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gZapiszPlik)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pListaSlowekLayout = new javax.swing.GroupLayout(pListaSlowek);
        pListaSlowek.setLayout(pListaSlowekLayout);
        pListaSlowekLayout.setHorizontalGroup(
            pListaSlowekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pListaSlowekLayout.setVerticalGroup(
            pListaSlowekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(eOpis)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pDodawania, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pListaSlowek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eOpis)
                .addGap(18, 18, 18)
                .addComponent(pListaSlowek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pDodawania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void pokazStrone(){
	listaSlowek.pokazStrone(((Container)listaSlowek.getComponent(1)).getComponents());
    }
    
    private void gZapiszPlikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gZapiszPlikActionPerformed
        usunZestaw(true);
    }//GEN-LAST:event_gZapiszPlikActionPerformed

    private void tfNumerZestawuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumerZestawuActionPerformed
        gZapisz.doClick();
    }//GEN-LAST:event_tfNumerZestawuActionPerformed

    private void gZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gZapiszActionPerformed
        usunZestaw(false);
    }//GEN-LAST:event_gZapiszActionPerformed


    public void usunZestaw(boolean czyZPliku){
	int numerZestawu = tfNumerZestawu.getText().equals("") ? -1 : Integer.parseInt(tfNumerZestawu.getText()) - 1;
	tfNumerZestawu.setText("");
	if(numerZestawu < 0 || numerZestawu >= ObslugaPliku.getPytania().size()){
	    if(!czyZPliku){
		JOptionPane.showMessageDialog(this, "Podaj prawidłowy numer zestawu.", "Nieprawidłowa wartość", JOptionPane.ERROR_MESSAGE);
		eKomunikat.setText("");
	    }else
		zapiszZmiany();
	    return;
	}
	    
        usunNa(numerZestawu);
	
	if(czyZPliku)
	    zapiszZmiany();
	
	if(ObslugaPliku.getPytania().size() == 0){
	    JOptionPane.showMessageDialog(this, "Plik jest pusty.");
	    edycja.dispose();
	}
	
	eKomunikat.setText("Pomyślnie usunięto.");
	
	// ZMIANA
	pokazStrone();
	
    }
    
    public void usunNa(int indeks){
        ObslugaPliku.getPytania().remove(indeks);
        ObslugaPliku.getOdpowiedzi().remove(indeks);
        ObslugaPliku.setIloscStron();
        ObslugaPliku.setCzyMaZawartosc(ObslugaPliku.getPytania().size() != 0);
	ListaKomponentowDoAktywacji.ustawKomponent(ObslugaPliku.getCzyMaZawartosc());
    }
    
    public void zapiszZmiany(){
	if(JOptionPane.showConfirmDialog(this, "Czy na pewno chcesz zapisać do pliku?", "Uwaga!", JOptionPane.YES_NO_OPTION) == 0){
	    String komunikat = ObslugaPliku.zapisDoPliku(ObslugaPliku.getPytania().toArray(), ObslugaPliku.getOdpowiedzi().toArray(), false);
	    if(!komunikat.equals("0")){
		JOptionPane.showMessageDialog(this, komunikat, "Nieudany zapis", JOptionPane.ERROR_MESSAGE);
		eKomunikat.setText("");
	    }else
		eKomunikat.setText("Pomyślnie zapisano do pliku.");
		
	}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eKomunikat;
    private javax.swing.JLabel eNumerZestawu;
    private javax.swing.JLabel eOpis;
    private javax.swing.JButton gZapisz;
    private javax.swing.JButton gZapiszPlik;
    private javax.swing.JPanel pDodawania;
    private javax.swing.JPanel pListaSlowek;
    private javax.swing.JTextField tfNumerZestawu;
    // End of variables declaration//GEN-END:variables
}
