/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package programodpytanie.paneleodpytania;

import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JTextField;
import programodpytanie.ObslugaOkienka;
import programodpytanie.ObslugaPliku;
import programodpytanie.Odpytanie;

/**
 *
 * @author Krzychu
 */
public class PanelPrzepytania extends javax.swing.JPanel {

    public static final String NAZWA_KLASY = "PanelPrzepytania";
    private CardLayout cl;
    private Odpytanie testOdpytania;
    
    private int numerPytania = 0;
    
    
    public PanelPrzepytania(Odpytanie testOdpytania) {
        initComponents();
	this.testOdpytania = testOdpytania;
    	this.cl = testOdpytania.getCardLayout();
        zadajPytanie();
	ustawEtykietyOdpowiedzi("", "", "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPytania = new javax.swing.JPanel();
        ePytanie = new javax.swing.JLabel();
        ePytaneSlowo = new javax.swing.JLabel();
        pTOdpowiedz = new javax.swing.JTextField();
        eJakaOdpowiedz = new javax.swing.JLabel();
        ePoprawnejOdp = new javax.swing.JLabel();
        eOdpowiedz = new javax.swing.JLabel();

        ePytanie.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        ePytanie.setText("Podaj po angielsku: ");

        ePytaneSlowo.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        ePytaneSlowo.setText("slowo");
        ePytaneSlowo.setToolTipText("");

        pTOdpowiedz.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        pTOdpowiedz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pTOdpowiedzActionPerformed(evt);
            }
        });

        eJakaOdpowiedz.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        eJakaOdpowiedz.setText("Dobra/Zła odpowiedź");

        ePoprawnejOdp.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        ePoprawnejOdp.setText("Poprawna odpowiedź to:");

        eOdpowiedz.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        eOdpowiedz.setText("odpowiedź");

        javax.swing.GroupLayout pPytaniaLayout = new javax.swing.GroupLayout(pPytania);
        pPytania.setLayout(pPytaniaLayout);
        pPytaniaLayout.setHorizontalGroup(
            pPytaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPytaniaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pPytaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPytaniaLayout.createSequentialGroup()
                        .addComponent(ePoprawnejOdp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eOdpowiedz))
                    .addComponent(eJakaOdpowiedz)
                    .addGroup(pPytaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pTOdpowiedz)
                        .addGroup(pPytaniaLayout.createSequentialGroup()
                            .addComponent(ePytanie)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ePytaneSlowo))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        pPytaniaLayout.setVerticalGroup(
            pPytaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPytaniaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPytaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ePytanie)
                    .addComponent(ePytaneSlowo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pTOdpowiedz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eJakaOdpowiedz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pPytaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ePoprawnejOdp)
                    .addComponent(eOdpowiedz))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pPytania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pPytania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pTOdpowiedzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pTOdpowiedzActionPerformed
        sprawdzOdpowiedz(((JTextField)evt.getSource()).getText());
	if(++numerPytania < ObslugaPliku.getPytania().size()){
	    zadajPytanie();
	    ((JTextField)evt.getSource()).setText("");
	}
	else
	    pokazWynik(PanelWyniku.NAZWA_KLASY);
    }//GEN-LAST:event_pTOdpowiedzActionPerformed
    
    private void zadajPytanie(){
	ePytaneSlowo.setText(ObslugaPliku.getPytania().get(numerPytania));
    }
    
    private void sprawdzOdpowiedz(String odpowiedz){
	if(odpowiedz.equals(ObslugaPliku.getOdpowiedzi().get(this.numerPytania))){
	    ustawEtykietyOdpowiedzi("Dobra odpowiedź!", "", "");
	    ObslugaPliku.setPoprawneOdpowiedzi();
	}else{
	    ustawEtykietyOdpowiedzi("Zła odpowiedź", "Poprawna odpowiedź to: ", ObslugaPliku.getOdpowiedzi().get(this.numerPytania));
	}
    }
    
    /**
     * Metoda ma za zadanie podmiankę etykiet. Przydaje się w trakcie odpytywania by ustawić poprawnie 
     * werdykt mówiący o tym czy ktoś podał prawidłową odpowiedź czy też złą (w przypadku złej wyświetlić
     * poprawną odpowiedź).
     * 
     * @param eWerdykt - odpowiada etykiecie <code>eJakaOdpowiedz</code>
     * @param eInfoOPoprawnej - odpowiada etykiecie <code>ePoprawnejOdp</code>
     * @param ePoprawnaOdpowiedz - odpowiada etykiecie <code>eOdpowiedz</code>
     */
    
    private void ustawEtykietyOdpowiedzi(String eWerdykt, String eInfoOPoprawnej, String ePoprawnaOdpowiedz){
	eJakaOdpowiedz.setText(eWerdykt);
	ePoprawnejOdp.setText(eInfoOPoprawnej);
	eOdpowiedz.setText(ePoprawnaOdpowiedz);
    }
    
    public void pokazWynik(String nazwaPanelu){
	testOdpytania.getPanelWyniku().myOptions();
        cl.show((Container)this.testOdpytania.getContentPane().getComponent(0), nazwaPanelu);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eJakaOdpowiedz;
    private javax.swing.JLabel eOdpowiedz;
    private javax.swing.JLabel ePoprawnejOdp;
    private javax.swing.JLabel ePytaneSlowo;
    private javax.swing.JLabel ePytanie;
    private javax.swing.JPanel pPytania;
    private javax.swing.JTextField pTOdpowiedz;
    // End of variables declaration//GEN-END:variables
}
