/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package programodpytanie.paneleodpytania;

import programodpytanie.ObslugaOkienka;
import programodpytanie.ObslugaPliku;
import programodpytanie.Ocena;

/**
 *
 * @author Krzychu
 */
public class PanelWyniku extends javax.swing.JPanel {

    public static final String NAZWA_KLASY = "PanelWyniku";
    
    public PanelWyniku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eNaglowekWyniku = new javax.swing.JLabel();
        eOpisOceny = new javax.swing.JLabel();
        eOcena = new javax.swing.JLabel();

        eNaglowekWyniku.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        eNaglowekWyniku.setText("Super/Nie za dobrze");

        eOpisOceny.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        eOpisOceny.setText("Twoja ocena to");

        eOcena.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        eOcena.setText("ocena (procenty)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eOpisOceny)
                        .addGap(18, 18, 18)
                        .addComponent(eOcena))
                    .addComponent(eNaglowekWyniku))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(eNaglowekWyniku)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eOpisOceny)
                    .addComponent(eOcena))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void myOptions(){
	for(Ocena ocena: ObslugaPliku.getOceny()){
	    double procenty = 100 * ObslugaPliku.getPoprawneOdpowiedzi() / ObslugaPliku.getOdpowiedzi().size();
	    if(ocena.czyWZakresie(procenty)){
		eNaglowekWyniku.setText(ocena.getKomunikat());
		eOcena.setText(ocena.getNazwa() + " (" + String.format("%.2f", procenty) + "%)" );
		break;
	    }    
	}
	ObslugaPliku.setPoprawneOdpowiedzi(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eNaglowekWyniku;
    private javax.swing.JLabel eOcena;
    private javax.swing.JLabel eOpisOceny;
    // End of variables declaration//GEN-END:variables
}
