/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package programodpytanie.paneledycji;

import programodpytanie.Edycja;
import java.awt.CardLayout;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import programodpytanie.ListaKomponentowDoAktywacji;
import programodpytanie.ObslugaPliku;

/**
 *
 * @author Komputer Domowy
 */
public class PanelNapiszPlik extends javax.swing.JPanel {

    public static final String NAZWA_KLASY = "PanelNapiszPlik";
    
    private Edycja edycja;
    
    private CardLayout cl;
    
    public PanelNapiszPlik(Edycja edycja) {
	this.edycja = edycja;
	this.cl = edycja.getCardLayout();
	initComponents();
	myOptions(edycja);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ptDane = new javax.swing.JTextArea();
        gWroc = new GuzikCofnij(edycja);
        gZapisz = new javax.swing.JToggleButton();
        gZapiszDoPliku = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jLabel1.setText("Dokonaj edycji pliku:");

        ptDane.setColumns(20);
        ptDane.setLineWrap(true);
        ptDane.setRows(5);
        jScrollPane1.setViewportView(ptDane);

        gWroc.setText("Wróć");

        gZapisz.setMnemonic('O');
        gZapisz.setText("Zapisz");
        gZapisz.setToolTipText("Zapisz w programie (alt + o)");
        gZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gZapiszActionPerformed(evt);
            }
        });

        gZapiszDoPliku.setMnemonic('S');
        gZapiszDoPliku.setText("Zapisz do pliku");
        gZapiszDoPliku.setToolTipText("Zapisz do pliku tekstowego (alt + S)");
        gZapiszDoPliku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gZapiszDoPlikuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gWroc)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gZapisz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gZapiszDoPliku)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gWroc)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(gZapisz)
                    .addComponent(gZapiszDoPliku))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gZapiszActionPerformed
        zapiszDoTablicy(false);
    }//GEN-LAST:event_gZapiszActionPerformed

    private void gZapiszDoPlikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gZapiszDoPlikuActionPerformed
        zapiszDoTablicy(true);
    }//GEN-LAST:event_gZapiszDoPlikuActionPerformed
     
    public void zapiszDoTablicy(boolean czyTezDoPliku){
	
	// Sprawdzanie poprawności zawartości pola tekstowego.
	
        boolean czyPoprawny = true;
        for(String linia: ptDane.getText().split("\\n")){
	    if(!ObslugaPliku.czyPoprawnaZawartoscPliku(linia)){
                czyPoprawny = false;
		System.out.println(ptDane.getText().indexOf(linia) + "\t" + (ptDane.getText().indexOf(linia) + linia.length()));
		ptDane.requestFocus();
		ptDane.select(ptDane.getText().indexOf(linia), ptDane.getText().indexOf(linia) + linia.length());
		JOptionPane.showMessageDialog(edycja, "Niepoprawidłowy format!\nOczekiwano: polskie słowo;angielskie słowo");		
		break;
	    }
	}
        
	// Zapis danych
	
        if(czyPoprawny){
            BufferedWriter bw = null;
            
            String linie[] = ptDane.getText().split("\\n");
            ObslugaPliku.getPytania().clear();
            ObslugaPliku.getOdpowiedzi().clear();
            
            if(czyTezDoPliku)
                czyTezDoPliku = JOptionPane.showConfirmDialog(edycja, "Czy na pewno chcesz zapisać do pliku?", "Uwaga!", JOptionPane.YES_NO_OPTION) == 0;
            
            if(czyTezDoPliku){
                try {
                    bw = new BufferedWriter(new FileWriter(ObslugaPliku.getPelnaNazwaPliku()));
                    bw.write("");
                    
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
                
            }
            
            for(int i = 0; i < linie.length; i++){
                String podzieloneLinie[] = linie[i].split(";");
                
		// Zapis do programu
                ObslugaPliku.getPytania().add(podzieloneLinie[0]);
                ObslugaPliku.getOdpowiedzi().add(podzieloneLinie[1]);
                
		// Zapis do pliku
                if(czyTezDoPliku){
                    try{
                        //System.out.println("Zpisano: " + linie[i]);
                        bw.append(linie[i] + "\n");
                    }catch(IOException ex){
                        try{
                            bw.close();
                        }catch (IOException ex1){
                            ex1.printStackTrace();
                        }finally{
                            ex.printStackTrace();
                            return;
                        }
                    }
                        
                }
                
                //System.out.println(ObslugaPliku.getPytania().get(i) + "\t" + ObslugaPliku.getOdpowiedzi().get(i));
                //if(ObslugaPliku.getPytania().get(i).equals(linie[i]))
            }
            
            ObslugaPliku.setIloscStron();
            ObslugaPliku.setCzyMaZawartosc(true);
            
	    ListaKomponentowDoAktywacji.ustawKomponent(ObslugaPliku.getCzyMaZawartosc());
            
            try {
                bw.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            
        }
        
    }
    
    public void myOptions(Edycja edycja){
	wstawDane();	
    }
    
    /**
     * Funkcja wstawia do pola tekstowego zawartość pliku (załadować dane z tablic, które zawierają
     * zawartość pliku).
     */
    public void wstawDane(){
	String dane = "";
	
	for(int i = 0; i < ObslugaPliku.getPytania().size(); i++){
	    dane += ObslugaPliku.getPytania().get(i) + ObslugaPliku.getGranicaSlow() + ObslugaPliku.getOdpowiedzi().get(i) + "\n";
	}
	
	ptDane.setText(dane);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gWroc;
    private javax.swing.JToggleButton gZapisz;
    private javax.swing.JButton gZapiszDoPliku;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ptDane;
    // End of variables declaration//GEN-END:variables
}
