package programodpytanie;

import java.awt.CardLayout;
import javax.swing.JPanel;
import programodpytanie.ObslugaOkienka;
import programodpytanie.paneledycji.PanelLista;
import programodpytanie.paneledycji.PanelNapiszPlik;

/**
 *
 * @author Komputer Domowy
 */
public class Edycja extends javax.swing.JFrame {

    ObslugaOkienka  obslugaOkienka = new ObslugaOkienka();
    
    public static final String NAZWA_PANELU = "eKtoraEdycja";
    private CardLayout cl = new CardLayout();
    
    public Edycja() {
	initComponents();
	myOptions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grKtoraEdycja = new javax.swing.ButtonGroup();
        pGlowny = new javax.swing.JPanel();
        pWyboruEdycji = new javax.swing.JPanel();
        eKtoraEdycja = new javax.swing.JLabel();
        rbNapiszPlik = new javax.swing.JRadioButton();
        rbWybierzZListy = new javax.swing.JRadioButton();
        gZatwierdzWybor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edytuj plik");

        pGlowny.setLayout(new java.awt.CardLayout());

        eKtoraEdycja.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        eKtoraEdycja.setText("Wybierz sposób edycji:");

        rbNapiszPlik.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        rbNapiszPlik.setText("Edytuj plik tekstowy");

        rbWybierzZListy.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        rbWybierzZListy.setSelected(true);
        rbWybierzZListy.setText("Wybór z listy");

        gZatwierdzWybor.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        gZatwierdzWybor.setText("Zatwierdź wybór");
        gZatwierdzWybor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gZatwierdzWyborActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pWyboruEdycjiLayout = new javax.swing.GroupLayout(pWyboruEdycji);
        pWyboruEdycji.setLayout(pWyboruEdycjiLayout);
        pWyboruEdycjiLayout.setHorizontalGroup(
            pWyboruEdycjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pWyboruEdycjiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pWyboruEdycjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(pWyboruEdycjiLayout.createSequentialGroup()
                        .addComponent(rbWybierzZListy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbNapiszPlik))
                    .addComponent(gZatwierdzWybor)
                    .addComponent(eKtoraEdycja))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pWyboruEdycjiLayout.setVerticalGroup(
            pWyboruEdycjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pWyboruEdycjiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eKtoraEdycja)
                .addGap(18, 18, 18)
                .addGroup(pWyboruEdycjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbWybierzZListy)
                    .addComponent(rbNapiszPlik))
                .addGap(7, 7, 7)
                .addComponent(gZatwierdzWybor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pGlowny.add(pWyboruEdycji, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(pGlowny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(pGlowny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gZatwierdzWyborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gZatwierdzWyborActionPerformed
        if(grKtoraEdycja.getSelection().getActionCommand() == "rbNapiszPlik")
	    stworzPanel(new PanelNapiszPlik(this), PanelNapiszPlik.NAZWA_KLASY);
	    
	    
	if(grKtoraEdycja.getSelection().getActionCommand() == "rbWybierzZListy")
	    stworzPanel(new PanelLista(this), PanelLista.NAZWA_KLASY);
	    
    }//GEN-LAST:event_gZatwierdzWyborActionPerformed

    public void myOptions(){
        
        this.setLocation(obslugaOkienka.getSrodekEkranu(this.getSize()));
        
        this.addWindowListener(obslugaOkienka);
        
	cl = (CardLayout)pGlowny.getLayout();
	
	grKtoraEdycja.add(rbNapiszPlik);
	grKtoraEdycja.add(rbWybierzZListy);
	
	rbNapiszPlik.setActionCommand("rbNapiszPlik");
	rbWybierzZListy.setActionCommand("rbWybierzZListy");
    }
    
    public void stworzPanel(JPanel panel, String nazwa){
	pGlowny.remove(0);
	pGlowny.add(panel, nazwa);
	//obslugaOkienka.setAllSize();
	this.setSize(this.getPreferredSize());
	this.setLocation(obslugaOkienka.getSrodekEkranu(this.getSize()));
	
    }
    
    public CardLayout getCardLayout(){
	return cl;
    }
    
    public JPanel getPWyboruEdycji(){
        return this.pWyboruEdycji; 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eKtoraEdycja;
    private javax.swing.JButton gZatwierdzWybor;
    private javax.swing.ButtonGroup grKtoraEdycja;
    private javax.swing.JPanel pGlowny;
    private javax.swing.JPanel pWyboruEdycji;
    private javax.swing.JRadioButton rbNapiszPlik;
    private javax.swing.JRadioButton rbWybierzZListy;
    // End of variables declaration//GEN-END:variables
}
