/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package programodpytanie;

import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Komputer Domowy
 */
public class ListaSlowek extends javax.swing.JPanel {
    
    private int nrStrony = 0;
    
    public ListaSlowek() {
	initComponents();
	setAktywnoscGuzikow();
	pokazStrone(pZawartoscPliku.getComponents());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pNaglowek = new javax.swing.JPanel();
        eNaglowek = new javax.swing.JLabel();
        pZawartoscPliku = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        gPokazLewo = new javax.swing.JButton();
        gPokazPrawo = new javax.swing.JButton();

        eNaglowek.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        eNaglowek.setText("Zawartość pliku");

        javax.swing.GroupLayout pNaglowekLayout = new javax.swing.GroupLayout(pNaglowek);
        pNaglowek.setLayout(pNaglowekLayout);
        pNaglowekLayout.setHorizontalGroup(
            pNaglowekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNaglowekLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(eNaglowek)
                .addGap(21, 21, 21))
        );
        pNaglowekLayout.setVerticalGroup(
            pNaglowekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNaglowekLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(eNaglowek)
                .addGap(21, 21, 21))
        );

        jLabel1.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        jLabel1.setText("jLabel1");

        jLabel2.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        jLabel2.setText("jLabel2");

        jLabel3.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        jLabel3.setText("jLabel3");

        jLabel4.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        jLabel4.setText("jLabel4");

        jLabel5.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        jLabel5.setText("jLabel5");

        jLabel10.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        jLabel10.setText("jLabel10");

        jLabel6.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        jLabel6.setText("jLabel6");

        jLabel9.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        jLabel9.setText("jLabel9");

        jLabel8.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        jLabel8.setText("jLabel8");

        jLabel7.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout pZawartoscPlikuLayout = new javax.swing.GroupLayout(pZawartoscPliku);
        pZawartoscPliku.setLayout(pZawartoscPlikuLayout);
        pZawartoscPlikuLayout.setHorizontalGroup(
            pZawartoscPlikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pZawartoscPlikuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pZawartoscPlikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(pZawartoscPlikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        pZawartoscPlikuLayout.setVerticalGroup(
            pZawartoscPlikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pZawartoscPlikuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pZawartoscPlikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pZawartoscPlikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pZawartoscPlikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pZawartoscPlikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pZawartoscPlikuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        gPokazLewo.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        gPokazLewo.setText("<===");
        gPokazLewo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gPokazLewoActionPerformed(evt);
            }
        });

        gPokazPrawo.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        gPokazPrawo.setText("===>");
        gPokazPrawo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gPokazPrawoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gPokazLewo)
                .addGap(43, 43, 43)
                .addComponent(gPokazPrawo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gPokazPrawo)
                    .addComponent(gPokazLewo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pNaglowek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pZawartoscPliku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pNaglowek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pZawartoscPliku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void myOptions(JPanel panel){
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(panel);
        panel.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createSequentialGroup()
	    .addComponent(this)
        );
        layout.setVerticalGroup(
            layout.createSequentialGroup()
	    .addComponent(this)
        );
    }
    
    private void gPokazLewoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gPokazLewoActionPerformed
        --this.nrStrony;
        setAktywnoscGuzikow();
        pokazStrone(pZawartoscPliku.getComponents());

    }//GEN-LAST:event_gPokazLewoActionPerformed

    private void gPokazPrawoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gPokazPrawoActionPerformed
        ++this.nrStrony;
        setAktywnoscGuzikow();
        pokazStrone(pZawartoscPliku.getComponents());
    }//GEN-LAST:event_gPokazPrawoActionPerformed

    private void setAktywnoscGuzikow(){
	gPokazLewo.setEnabled(!(nrStrony == 0));
	gPokazPrawo.setEnabled(!(nrStrony == ObslugaPliku.getIloscStron() - 1));
    }
    
    public void pokazStrone(Component[] etykiety){
	for(int i = 0; i < etykiety.length; i++){
	    JLabel tmp = ((JLabel)etykiety[i]);
	    try{
		String pozycja = (i + 1 + (this.nrStrony * 10)) + ". " + ObslugaPliku.getPytania().get(i + (this.nrStrony * 10)) + " - " + ObslugaPliku.getOdpowiedzi().get(i + (this.nrStrony * 10));
		tmp.setText(pozycja);
	    }catch(IndexOutOfBoundsException e){
		tmp.setText(" ");
	    }
	}
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eNaglowek;
    private javax.swing.JButton gPokazLewo;
    private javax.swing.JButton gPokazPrawo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pNaglowek;
    private javax.swing.JPanel pZawartoscPliku;
    // End of variables declaration//GEN-END:variables
}
