/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programodpytanie;

import java.awt.AWTEvent;
import java.awt.event.*;
import java.util.EventObject;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.*;
/**
 *
 * @author Komputer Domowy
 */
public class Main extends javax.swing.JFrame {

    private ObslugaOkienka obslugaOkienka = new ObslugaOkienka();
    
    public Main() {
	this.addWindowListener(obslugaOkienka);
	ObslugaPliku.przygotujFoldery();
	ObslugaPliku.czytanieOcen(ObslugaPliku.getPelnaNazwaPlikuOcen(), true);
	
	initComponents();
	myOptions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pOtworzPoNazwie = new javax.swing.JPanel();
        eOtworzPoNazwie = new javax.swing.JLabel();
        pTOtworzPoNazwie = new javax.swing.JTextField();
        pOtworzZListy = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lPlikowDoOtwarcia = new javax.swing.JList<>();
        eOtworzZListy = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Odpytanie!");
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(500, 400));
        setSize(this.getPreferredSize());

        eOtworzPoNazwie.setFont(ObslugaOkienka.CZ_NAGLOWEK);
        eOtworzPoNazwie.setLabelFor(pTOtworzPoNazwie);
        eOtworzPoNazwie.setText("Podaj nazwę pliku, na którym chcesz pracować:");

        pTOtworzPoNazwie.setColumns(25);
        pTOtworzPoNazwie.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        pTOtworzPoNazwie.setText(ObslugaPliku.getNazwaPliku());

        javax.swing.GroupLayout pOtworzPoNazwieLayout = new javax.swing.GroupLayout(pOtworzPoNazwie);
        pOtworzPoNazwie.setLayout(pOtworzPoNazwieLayout);
        pOtworzPoNazwieLayout.setHorizontalGroup(
            pOtworzPoNazwieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOtworzPoNazwieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pTOtworzPoNazwie)
                .addGap(51, 51, 51))
            .addGroup(pOtworzPoNazwieLayout.createSequentialGroup()
                .addComponent(eOtworzPoNazwie)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pOtworzPoNazwieLayout.setVerticalGroup(
            pOtworzPoNazwieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOtworzPoNazwieLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(eOtworzPoNazwie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pTOtworzPoNazwie, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        lPlikowDoOtwarcia.setFont(ObslugaOkienka.CZ_STANDARDOWA);
        lPlikowDoOtwarcia.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = ObslugaPliku.stworzListePlikow();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        }
    );
    jScrollPane1.setViewportView(lPlikowDoOtwarcia);

    eOtworzZListy.setFont(ObslugaOkienka.CZ_NAGLOWEK);
    eOtworzZListy.setText("Lub wybierz plik z listy");

    javax.swing.GroupLayout pOtworzZListyLayout = new javax.swing.GroupLayout(pOtworzZListy);
    pOtworzZListy.setLayout(pOtworzZListyLayout);
    pOtworzZListyLayout.setHorizontalGroup(
        pOtworzZListyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pOtworzZListyLayout.createSequentialGroup()
            .addComponent(eOtworzZListy)
            .addGap(0, 0, Short.MAX_VALUE))
        .addGroup(pOtworzZListyLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGap(90, 90, 90))
    );
    pOtworzZListyLayout.setVerticalGroup(
        pOtworzZListyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pOtworzZListyLayout.createSequentialGroup()
            .addComponent(eOtworzZListy)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
            .addGap(55, 55, 55))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap(41, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(pOtworzPoNazwie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pOtworzZListy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(41, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(pOtworzPoNazwie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(pOtworzZListy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void myOptions(){
        pTOtworzPoNazwie.addActionListener((ActionEvent e) -> {
	    czytSciezkiPliku(e);
	});
	lPlikowDoOtwarcia.addListSelectionListener((ListSelectionEvent e) -> {
	    czytSciezkiPliku(e);
	});
	this.setLocation(obslugaOkienka.getSrodekEkranu(this.getSize()));
        
        pTOtworzPoNazwie.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                pTOtworzPoNazwie.select(0, (pTOtworzPoNazwie.getText()).length());
            }
        });
    }
    
    private void czytSciezkiPliku(EventObject e){
	String nazwaPliku = "";
	if(e.getSource() instanceof JTextField){
	    if(((JTextField)((ActionEvent)((AWTEvent)e)).getSource()) == pTOtworzPoNazwie)
		nazwaPliku = pTOtworzPoNazwie.getText();
	}else if(e.getSource() instanceof JList){
	    if(((JList)((ListSelectionEvent)e).getSource()) == lPlikowDoOtwarcia)
	    nazwaPliku = (String)((JList)((ListSelectionEvent)e).getSource()).getSelectedValue();
	}
	
	String komunikat = ObslugaPliku.setNazwaPliku(nazwaPliku);
	if(!komunikat.equals("0")){
	    JOptionPane.showMessageDialog(this, komunikat);
	}else if(!ObslugaPliku.czyIstniejePlik(this)){}
	else if(!(komunikat = ObslugaPliku.czytanieZPliku(ObslugaPliku.getPelnaNazwaPliku(), true)).equals("0")){
	    JOptionPane.showMessageDialog(this, komunikat);
	}else{
	    this.dispose();
	    new Menu().setVisible(true);
	}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Main().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eOtworzPoNazwie;
    private javax.swing.JLabel eOtworzZListy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lPlikowDoOtwarcia;
    private javax.swing.JPanel pOtworzPoNazwie;
    private javax.swing.JPanel pOtworzZListy;
    private javax.swing.JTextField pTOtworzPoNazwie;
    // End of variables declaration//GEN-END:variables
}
