package programodpytanie;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import programodpytanie.paneleodpytania.PanelPrzepytania;
import programodpytanie.paneleodpytania.PanelWyniku;

public class Odpytanie extends JFrame {
    
    private ObslugaOkienka obslugaOkienka = new ObslugaOkienka();
    private PanelWyniku panelWyniku = new PanelWyniku();
    private CardLayout cl;
    
    public Odpytanie() {
        this.addWindowListener(obslugaOkienka);
        initComponents();
        myOptions();
    }
    
    public PanelWyniku getPanelWyniku(){
	return panelWyniku;
    }
    
    public CardLayout getCardLayout(){
	return cl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pGlowny = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Odpytywanie!");

        pGlowny.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(pGlowny, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(pGlowny, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void myOptions(){
        this.setLocation(obslugaOkienka.getSrodekEkranu(this.getSize()));
        this.cl = (CardLayout)pGlowny.getLayout();
        pGlowny.add(new PanelPrzepytania(this), PanelPrzepytania.NAZWA_KLASY);
        pGlowny.add(panelWyniku, PanelWyniku.NAZWA_KLASY);
    }
    
    /*public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestOdpytania().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pGlowny;
    // End of variables declaration//GEN-END:variables
}
